fit

diff --git a/scripts/install_utils b/scripts/install_utils
--- a/scripts/install_utils
+++ b/scripts/install_utils
@@ -44,6 +44,16 @@ build_frontend() {
   fi
 }
 
+build_frontend_win() {
+  if frontend/gradlew.bat -p frontend clean build;
+    then
+    echo "Frontend build suite execution successful"
+  else
+    echo "Frontend build suite execution failed!!! Check logs for more details"
+    exit 1
+  fi
+}
+
 run_backend_pytest()
 {
   if python -m pytest --cov-report html:htmlcov --cov=ts/ ts/tests/unit_tests/;
