fit

diff --git a/scripts/install_from_src_windows b/scripts/install_from_src_windows
--- a/scripts/install_from_src_windows
+++ b/scripts/install_from_src_windows
@@ -6,8 +6,36 @@ echo "                      If you don't want to proceed kill this script in the
 echo "                      =============================================="
 
 sleep 10
-clean_slate
-build_frontend_win
-build_install_server
-build_install_archiver
-clean_up_build_residuals
+echo "Cleaning up state"
+# uninstall any global installations
+pip uninstall --yes torchserve || true
+pip uninstall --yes torch-model-archiver || true
+sleep 5
+
+if frontend/gradlew.bat -p frontend clean build;
+  then
+  echo "Frontend build suite execution successful"
+else
+  echo "Frontend build suite execution failed!!! Check logs for more details"
+  exit 1
+fi
+
+pip install .
+
+echo $PWD
+cd model-archiver
+if pip install .;
+then
+  echo "Successfully installed torch-model-archiver"
+else
+  echo "torch-model-archiver installation failed"
+  exit 1
+fi
+cd ..
+
+rm -rf ts/__pycache__/
+rm -rf ts/metrics/__pycache__/
+rm -rf ts/protocol/__pycache__/
+rm -rf ts/utils/__pycache__/
+rm -rf frontend/modelarchive/build
+rm -rf frontend/server/build
